Renewed: Improve Styling
FalveyLibraryTechnology/VuDL pull request #337
Opened 2024-10-31 20:53 UTC by crhallberg

Splitting the style part of #258 into a new PR. Some of the JSX syntax has been copied over, but mostly this was re-themed from scratch. This work has revealed some redundancies that can be addressed here or in a new PR.

2024-11-01 13:26 UTC, demiankatz requested changes
Thanks, @crhallberg -- we should probably get the build passing before I review this closely, especially if it's just formatting that's causing the failure. You should be able to `npm run format` to auto-fix styles (can't remember if this will work from the top level folder, but at very least I'm pretty sure it will work from inside the `client` folder).

2024-11-01 13:26 UTC, demiankatz commented
From looking at the failed build, some of the issues seem to be related to unused variables, so it's not just auto-fixable whitespace that's an issue.

2024-11-05 20:01 UTC, demiankatz commented
@crhallberg, looks like we're down to just one failing test, and it appears to be a trivial whitespace issue. Nearly there! Let me know when you're ready for me to look closer. :-)

2024-11-21 15:06 UTC, demiankatz requested changes
Haven't taken too deep of a dive yet, but this is generally looking nicer all around. However, I'm noticing that the delete icons are wrapping to a second line and looking weird; e.g.:

![image](https://github.com/user-attachments/assets/5fb0acca-5327-4c69-88b3-9852ecdbfa3a)

2024-11-21 15:08 UTC, demiankatz commented on client/components/edit/ObjectStatus.tsx
> +        case "Inactive":
I think we need a better icon here for deleted -- the default question mark is weird on deleted items.

2025-01-14 19:06 UTC, crhallberg commented on client/components/edit/ObjectStatus.tsx
> +        case "Inactive":
I added [a new icon for "Deleted"](https://mui.com/material-ui/material-icons/?query=remove&selected=Close), which is the right status as far as I can tell via grepping.

2025-01-14 19:39 UTC, crhallberg commented
Could it prettier? Always. Is it better? YES!

2025-01-15 13:19 UTC, demiankatz commented
On smaller screen sizes, the bottom row of paginator buttons have gotten a bit weird. Here's what they look like on live:

![image](https://github.com/user-attachments/assets/fc34b424-508a-4d1f-a784-31c53f4164f9)

And here's what they look like in this branch, in my VM, on my laptop screen:

![image](https://github.com/user-attachments/assets/4b3af790-88c7-4fc1-9396-4cfa65351ddd)

The warning color of the delete button is gone, and the sizing is just weird. :-)

2025-01-15 13:36 UTC, demiankatz requested changes
Thanks for fixing the delete status icon, @crhallberg -- that's definitely better. However, the delete action button is still problematic. I also found issues with the delete button appearance in the paginator. I have created TODO checkboxes for these two issues and linked the descriptions to comments with screen shots.

Some other general observations that might be worth addressing:

- I've noticed that tool tips in the editor only seem to work if you hover over the text and icons of the buttons. If you hover inside the button without touching the button content, you don't get a tool tip. This seems like it could cause problems/confusion, especially on the delete button which currently has a huge button with a tiny icon in the middle of it.
- I find the new "black on white" buttons kind of boring; I felt the old "white on dark blue" buttons felt more button-y. Maybe this is necessary for accessibility or dark mode support, in which case I can live with it... but I miss the old look.
- The "Show Thumbnails / Show Models / Show Child Counts" buttons in the editor are floated left now, but used to be floated right. I kind of prefer "controls on right" unless you have a strong reason for this change.
- On the "edit object" page, the buttons have gotten very large and spaced out; I think these controls could be made a bit more compact without accessibility suffering.
- On the "edit object" page, the green "populated datastream" color has turned yellow; I think it's important for this to be green.
- The colors for the object status (active/inactive/deleted) icons also feel too subtle to me. The inactive yellow is hard to distinguish from the deleted red. I wonder if a subtle background color on the control would be a better way to color-flag these than using a foreground color on a tiny icon.
- The fonts in the contents list feel smaller than necessary. Gives me more of a cramped feeling than the previous design, even though things line up more neatly.

Hopefully none of these things are terribly hard to change, and feel free to disagree with me on anything you feel strongly about. After we've done another round or two of this, we should get more opinions involved -- maybe by sending screen shots to the DCDE team.

2025-04-03 17:04 UTC, crhallberg commented
> * I've noticed that tool tips in the editor only seem to work if you hover over the text and icons of the buttons.

> * On the "edit object" page, the green "populated datastream" color has turned yellow; I think it's important for this to be green.

For these two items, I might need a screenshot to point me to the right location.

2025-04-03 17:41 UTC, demiankatz commented
@crhallberg, I'm no longer seeing a tool tip problem, though maybe I'm forgetting what I meant in my original message.

Regarding populated datastreams, I'm referring to the area of the object editor (e.g. `http://localhost:3000/edit/object/vudl:1`) that lists the datastreams. Here's what it looks like in dev:

![image](https://github.com/user-attachments/assets/9c754228-7c04-450a-9a2f-a0c7c4257b32)

And here's what it looks like in this PR:

![image](https://github.com/user-attachments/assets/dfcd5f77-1a62-4345-ae0c-ac8a9a13d3c3)

I think we need to keep the green color (or something close to it) if at all possible. I'm also not a fan of the lack of separation or the incredibly tiny icons in the new version. What do you think?

2025-04-10 16:24 UTC, demiankatz requested changes
Thanks, @crhallberg, things are definitely improved with the latest changes.

See below for a couple of things I noticed during a (less than exhaustive) review of the latest code.

I also think something needs to be done about the object button bar, because the delete button currently wraps to a second line and has no label; it would be nice to make this more consistent and balanced somehow.

![image](https://github.com/user-attachments/assets/eb46acb5-6b03-4f50-b2b9-c4935675945f)

2025-04-10 16:24 UTC, demiankatz commented on client/components/edit/children/ChildList.tsx
> +            <p class={styles.childlist__pagination}>
Why the change to `class` here? I thought that was illegal in React and `className` had to be used.

2025-04-10 16:24 UTC, demiankatz commented on client/components/edit/ObjectButtonBar.module.css
> +.objectBar {
Indentation looks weird in this file; I think you have a mix of tabs and spaces. Can you standardize on tabs? (Maybe a bad IDE setting?).

2025-04-14 20:05 UTC, crhallberg commented
I don't see the delete buttons in the ObjectBar. Is there a setting I need to turn on?

2025-04-15 10:56 UTC, demiankatz commented on client/components/edit/ObjectButtonBar.module.css
> +.objectBar {
Sorry, I phrased this badly -- we should standardize our tabs to use spaces. "Standardize on tabs" is not what I meant, and was the worst possible way I could have said that. ;-)

2025-04-15 10:58 UTC, demiankatz commented
> I don't see the delete buttons in the ObjectBar. Is there a setting I need to turn on?

The delete button only appears if you have a Trash PID set in your vudl.ini -- see:

https://github.com/FalveyLibraryTechnology/VuDL/blob/dev/api/vudl.ini.dist#L36

(You just need to create a folder somewhere that will serve as your trash can, and then put that PID in the config file).

I forgot about this requirement -- sorry for the confusion!

2025-04-24 20:16 UTC, crhallberg commented on client/components/edit/ObjectButtonBar.module.css
> +.objectBar {
Fixed

2025-04-24 20:17 UTC, crhallberg commented on client/components/edit/children/ChildList.tsx
> +            <p class={styles.childlist__pagination}>
Fixed

2025-04-25 16:58 UTC, demiankatz commented on client/components/edit/ObjectButtonBar.module.css
> +.objectBar {
There were still a lot of tabs in the diffs introduced here. I just did a global search and replace to change \t to four spaces, resulting in commit c503f4238a0f22ca01e0d13cb72f9561955068e1 -- hopefully that has taken care of everything.

2025-04-25 17:13 UTC, demiankatz requested changes
Thanks, @crhallberg, this is looking really great -- I think we're nearly done. Just a few remaining things:

1.) I just updated snapshots, but there's still one failing test. Let me know if you need help figuring out what's going on. I think it may be directly related to my next question, which is...

2.) Why did you remove the "loading" status support from DatastreamControlButton? I think that was intended to prevent buttons from being pressed before the associated content had loaded. Maybe you refactored that code elsewhere... but just want to be sure it's safe and accounted for!

3.) There's an empty client/styles/object-editor.css file added in this PR. Is that actually used/needed?

2025-05-07 16:02 UTC, demiankatz requested changes
Thanks, @crhallberg -- just a couple small questions. Once these are settled, I think the next task is to take a bunch of before and after screen shots so we can get feedback from DCDE.

2025-05-07 16:02 UTC, demiankatz commented on client/styles/global.css
> +svg.css-i4bv87-MuiSvgIcon-root {
Any idea what the `i4bv87` here means? Just wondering if this is going to be fragile styling when a new version of MUI comes out, if this is all auto-generated.

2025-05-07 16:02 UTC, demiankatz commented on client/styles/vendor/colors-harmony.css
> +:root {
If this is a vendor file, we should offer some indication of license and source; maybe a parallel text file if there's no better way.

2025-05-07 16:02 UTC, demiankatz commented on client/styles/vendor/colors-tailwindcss.css
> +:root {
Same here -- should document source.

2025-05-27 16:58 UTC, crhallberg commented on client/styles/global.css
> +svg.css-i4bv87-MuiSvgIcon-root {
This is an artifact of the CSS modules - and I shouldn't be relying on it.

2025-05-28 19:53 UTC, demiankatz requested changes
Thanks! I'll start taking screen shots the next time I am able to spin up an instance of this. In the meantime, just one trivial stylistic issue -- since we currently use spaces everywhere else, we shouldn't start introducing tabs in selected files. :-)

2025-05-28 19:53 UTC, demiankatz commented on client/components/edit/datastream/DatastreamControlButton.module.css
> +	font-size: 16pt;
This file seems to be using tabs instead of spaces.

2025-06-19 13:32 UTC, demiankatz requested changes
While testing this today, I noticed this message during build: `autoprefixer: end value has mixed support, consider using flex-end instead` -- should we make adjustments?

2025-06-19 13:41 UTC, demiankatz commented
In any case, as promised, here's a set of screen shots to allow us to compare the new and old styles:

| Context | Old Image | New Image |
| ------- | ----------| -------------|
| Main Menu | <img width="960" alt="mainmenu-old" src="https://github.com/user-attachments/assets/5eac207c-1d7c-4c5b-8cd9-4095273f4e0e" /> | <img width="960" alt="mainmenu-new" src="https://github.com/user-attachments/assets/512ffd5a-8b1d-479a-8096-c316563002bf" />|
| Pagination Menu | <img width="960" alt="paginationmenu-old" src="https://github.com/user-attachments/assets/f54fd732-3806-410f-9853-a01e75dca355" /> |  <img width="960" alt="paginationmenu-new" src="https://github.com/user-attachments/assets/48064dd9-3fce-46d6-a138-4ba6dbd10daa" />|
| Paginator | <img width="960" alt="paginator-old" src="https://github.com/user-attachments/assets/105c784d-1160-4502-8812-f942979ef905" /> | <img width="960" alt="paginator-new" src="https://github.com/user-attachments/assets/011d3c4a-c5c3-4d3a-9646-cd5bfd063d8d" /> |
| Editor (top-level) | <img width="960" alt="editor-old" src="https://github.com/user-attachments/assets/19b53d18-6996-4764-a1ec-0e443f93fc48" /> |  <img width="960" alt="editor-new" src="https://github.com/user-attachments/assets/377ceb20-8f11-4ddc-a582-c8686146325a" /> |
| Editor (object) | <img width="960" alt="editorobject-old" src="https://github.com/user-attachments/assets/e7575b07-1d26-492e-8f78-6774ba08f075" /> |  <img width="960" alt="editorobject-new" src="https://github.com/user-attachments/assets/9f9eaa25-32d7-420d-9031-fe18ebab6498" /> |
| Editor (Dublin Core) |  <img width="960" alt="editorobjectdc-old" src="https://github.com/user-attachments/assets/75b61644-d6e1-42c1-bea2-4ebf94a49533" /> |  <img width="960" alt="editorobjectdc-new" src="https://github.com/user-attachments/assets/13cf71a1-3657-4a13-a88f-383e32894cad" /> |
| Bulk Editor |  <img width="960" alt="bulkeditor-old" src="https://github.com/user-attachments/assets/86191939-c838-4f8c-b279-d507a64f2cbf" /> | <img width="960" alt="bulkeditor-new" src="https://github.com/user-attachments/assets/790e9584-0134-46f6-bae1-1e2a5ba7a9df" /> |

2025-12-19 20:16 UTC, crhallberg commented
- Tabs are now spaces.
- autoprefixer is happy.
- [New color palette](https://www.radix-ui.com/colors) bc I am too powerful and you cannot stop me.

2025-12-27 21:18 UTC, demiankatz approved these changes
Thanks, @crhallberg! Looks good now!

2025-12-27 21:19 UTC, merged